version: '3.1'
services:
  web:
    image: easy-fyi-image
    restart: always
    ports:
      - "3001:3000"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: myroot
      POSTGRES_USER: easyfyi
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: null
      POSTGRES_USER: easyfyi
  #vault:
    #image: vault
    #ports:
      #- "8200:8200"
    #restart: always
    #cap_add:
     #- IPC_LOCK
    #environment:
      #VAULT_DEV_ROOT_TOKEN_ID: myroot
